name: first-workflow
on: workflow_dispatch
jobs:
  first-job:  
    runs-on: ubuntu-latest
    steps: 
      - name: Print Hello
        run: |
          echo "Hello"
          echo "hw r u?"
      - name: Print Bye
        run: echo "Bye"
      
    
